title: Nicolie Olie Art
description: I'm Nicole. This blog is for my doodles (and oodles of thoughts).
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog


# Social settings
instagram_url: https://instagram.com/nicolieolieart
github_url: https://github.com/nicolejavorsky
